# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-10 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rushee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('grade', models.CharField(choices=[('FRESHMAN', 'FR'), ('SOPHOMORE', 'SO'), ('JUNIOR', 'JR'), ('SENIOR', 'SR')], max_length=2)),
                ('phone_number', models.IntegerField(default=0)),
                ('brothers_known', models.CharField(blank=True, max_length=300, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('FIRST', '1'), ('SECOND', '2'), ('BID_ROOM', 'BID'), ('ACCEPTED', 'A'), ('HOLDING', 'H'), ('DENIED', 'D')], max_length=10)),
            ],
        ),
    ]
