# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-11 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190711_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='rushee',
            name='comments',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
