# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-11 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rushee_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushee',
            name='grade',
            field=models.CharField(choices=[('FRESHMAN', 'FR'), ('SOPHOMORE', 'SO'), ('JUNIOR', 'JR'), ('SENIOR', 'SR')], max_length=100),
        ),
    ]
