# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-11 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190711_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushee',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='status',
            field=models.CharField(choices=[('FIRST', '1'), ('SECOND', '2'), ('ACCEPTED', 'A'), ('HOLDING', 'H'), ('DENIED', 'D')], max_length=10),
        ),
    ]
