# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-11 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_rushee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushee',
            name='status',
            field=models.CharField(choices=[('FIRST', 'Main Floor'), ('SECOND', 'Upstairs'), ('ACCEPTED', 'Accepted'), ('HOLDING', 'Holding'), ('DENIED', 'Denied')], max_length=10),
        ),
    ]
