# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-11 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rushee',
            name='comments',
        ),
    ]
