# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-22 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='brother',
        ),
    ]
