# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-05 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_comment_brother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushee',
            name='grade',
            field=models.CharField(choices=[('FRESHMAN', 'FRESHMAN'), ('SOPHOMORE', 'SOPHOMORE'), ('JUNIOR', 'JUNIOR'), ('SENIOR', 'SENIOR')], max_length=100),
        ),
    ]
