# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-16 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20190805_0954'),
        ('website', '0013_auto_20190816_1553'),
    ]

    operations = [
    ]
