# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-16 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20190816_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='rushee',
            name='upstairs_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
