# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-16 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_rushee_upstairs_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushee',
            name='upstairs_room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
